### ISSUE TITLE
Problems installing on mac, python 3.4.1

### ISSUE THREAD

**Issue by luckydonald** [ZeevG/python-forecast.io#27]
Maybe you can have a look, not sure if it is related to your package, but other modules did install.
```Python
Install packages failed: Error occurred when installing package python-forecastio. 

The following command was executed:

packaging_tool.py install --build-dir /private/var/folders/gj/84mj91y514z79t19xfc8t8sr0000gn/T/pycharm-packaging5452297355347498062.tmp --user python-forecastio

The error output of the command:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/helpers/packaging_tool.py", line 56, in do_install
    import pip
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/__init__.py", line 10, in <module>
    from pip.util import get_installed_distributions, get_prog
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/util.py", line 18, in <module>
    from pip._vendor.distlib import version
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
    from .compat import string_types
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/helpers/packaging_tool.py", line 125, in main
    retcode = do_install(pkgs)
  File "/Applications/PyCharm.app/helpers/packaging_tool.py", line 58, in do_install
    error_no_pip()
  File "/Applications/PyCharm.app/helpers/packaging_tool.py", line 36, in error_no_pip
    tb = sys.exc_traceback
AttributeError: 'module' object has no attribute 'exc_traceback'
```

**Comment by luckydonald** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 425: ordinal not in range(128)

**Comment by luckydonald** [comment]
While Command line works again.
```
(virtualenv3.4.3)mac-2:telegram-bot luckydonald$ pip install python-forecastio
Collecting python-forecastio
  Using cached python-forecastio-1.3.1.tar.gz
Collecting requests>=1.6 (from python-forecastio)
  Downloading requests-2.5.3-py2.py3-none-any.whl (468kB)
    100% |################################| 471kB 573kB/s
Installing collected packages: requests, python-forecastio

  Running setup.py install for python-forecastio
Successfully installed python-forecastio-1.3.1 requests-2.5.3
```

**Comment by ZeevG** [comment]
Interestingly there was a strange, completely unnecessary UTF-8 char in that position! I've now removed it and incremented the patch version.

The problematic character was one of these http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=0x2019&mode=hex

It looks like maybe @DannyGoodall has also been running into this problem https://github.com/DannyGoodall/python-forecast.io/commit/52b7f4c92e3de21c1fa3674fc819187dee50d839
